Bug - kojira expects repos-dist directory
None of the Koji documentation mentions this requirement as part of the
skeleton tree, but without this, Kojira belches out something like the
following every minute:

2017-09-11 17:24:44,641 [ERROR] koji: Traceback (most recent call last):
  File "/usr/sbin/kojira", line 652, in main
    repomgr.pruneLocalRepos(distrepodir, 'dist_repo_lifetime')
  File "/usr/sbin/kojira", line 353, in pruneLocalRepos
    for tag in os.listdir(topdir):
OSError: [Errno 2] No such file or directory: '/mnt/koji/repos-dist'